project:
  type: website

website:
  title: "Linus Chirchir"
  description: "Data Scientist"
  page-navigation: true
  back-to-top-navigation: true
  favicon: /images/logo.png
  twitter-card:
    site: "@linuschirchir"
  open-graph: true
  site-url: https://linuschirchir.com
  repo-url: https://github.com/linuschirchir/linuschirchir.github.io
  repo-actions: [edit, issue]
  cookie-consent:
    type: express
    prefs-text: "Change cookies ðŸª"
  # If you are forking our repo to develop content -- whether for Linus Chirchir 
  # or your own purposes -- please disable our Google Analytics tag during development.
  # If building your own site, replace our GA tag with your own GA tag before deployment.
  # This will prevent your activity being tracked and counted in our analytics dashboard.
  # Thank you!
  google-analytics: "G-G006R9PLWE"
  navbar:
    toggle-position: right
    logo-href: https://linuschirchir.com/
    logo: images/logo.png
    logo-alt: "Linus Chirchir Logo"
    title: false
    collapse-below: lg
    left:
    - text: Home
      icon: house-fill
      href: index.qmd
    - text: Projects
      icon: clipboard-check-fill
      href: projects.qmd
    - text: CV
      icon: person-lines-fill
      href: cv.qmd
    - text: Blog
      icon: journal-text
      href: blog.qmd
    right:
    - icon: linkedin
      aria-label: LinkedIn
      href: https://www.linkedin.com/in/LinusChirchir/
      target: _blank
    - icon: github
      aria-label: GitHub
      href: https://github.com/LinusChirchir
      target: _blank
    - icon: facebook
      aria-label: Facebook
      href: https://facebook.com/ChirchirLinus1
      target: _blank
    - icon: twitter-x
      aria-label: Twitter/X
      href: https://x.com/LinusChirchir
      target: _blank
    - icon: envelope
      aria-label: Contact
      href: mailto:linus@linuschirchir.com
      target: _blank
  page-footer:
    background: "#4169E1"
    left: >-
      Copyright &#169; 2024 Linus Chirchir
    right:
      - text: "Accessibility"
        href: accessibility.qmd
        aria-label: Accessibility Commitment
      - text: "Code of Conduct"
        href: coc.qmd
        aria-label: Code of Conduct
      - text: "Contact"
        href: contact.qmd
        aria-label: Contact
      - text: "Licence"
        href: licence.qmd
        aria-label: Licence Details
format:
  html:
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    theme:
      light: [cosmo, light.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#4169E1"

execute:
  freeze: true
  warning: false